Models/Paiement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HTPIFoundation.Models
{
    public class Paiement
    {
        public int ID   { get; set; }
        public int MembreID   { get; set; }
        [Display(Name = "Montant payé *")]
        public Decimal MontantPayer   { get; set; }
        [Display(Name = "Date de paiement *")]
        public DateTime DatePayement   { get; set; }
        [Display(Name = "Moyen de paiement *")]
        public int MoyenPayement   { get; set; }
        [Display(Name = "ID Transaction *")]
        public string IDTransaction   { get; set; }
        [Display(Name = "Avance accordée *")]
        public Boolean AvanceAccord   { get; set; }
        [Display(Name = "Montant de l’avance * ")]
        public Decimal MontantAvance   { get; set; }
        [Display(Name = "ID du membre qui a avancé l’avance *")]
        public int? MembreAvanceID  { get; set; }

        [NotMapped]
        public string MembreReference { get; set; }

        public Membre Membre   { get; set; }
        public Membre MembreAvance { get; set; }
    }
}

Controllers/MembreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HTPIFoundation.Models;
using Microsoft.AspNetCore.Http;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace HTPIFoundation.Controllers
{
    public class MembreController : Controller
    {
        private readonly HTPIFoundationContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public MembreController(HTPIFoundationContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            this._hostingEnvironment = hostingEnvironment;
        }

        // GET: Membre
        public async Task<IActionResult> Index()
        {
            return View(await _context.Membre.Include("Pays").ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Login([FromForm] Admin admin)
        {
            Utilisateur user = await _context.Utilisateur.Where(u => u.Email == admin.email && u.Password == admin.password).FirstOrDefaultAsync();
            if(user != null)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Index", "Administrateur");
            }
        }

        // GET: Membre/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membre.Include("PieceIdentite").Include("PieceIdentite.TypePieceIdentite").Include("PieceIdentite.PaysDelivrance")
                .Include("PieceIdentite.TypeJustDomicile").Include("Operateur").Include("PersonneReference")
                .SingleOrDefaultAsync(m => m.ID == id);
            if (membre == null)
            {
                return NotFound();
            }

            ViewBag.UploadPieceIdentiteID = membre.PieceIdentite.UploadPieceIdentiteID;
            ViewBag.UploadJustificatifDomicileID = membre.PieceIdentite.UploadJustificatifDomicileID;
            ViewBag.UploadExtraitActeNaissanceID = membre.PieceIdentite.UploadActeDeNaissanceID;

            return View(membre);
        }

        // GET: Membre/Create
        public IActionResult Create()
        {
            ViewBag.Operateurs = _context.Operateur.ToList();
            ViewBag.TypePieceIdentites = _context.TypePieceIdentite.ToList();
            ViewBag.TypeJustDomiciles = _context.TypeJustificatifDomicile.ToList();
            ViewBag.Pays = _context.Pays.ToList();
            ViewBag.Saved = 0;
            return View();
        }

        [HttpPost]
        public JsonResult GetPays([FromBody] Term term){
            var res = _context.Pays.Where(p => p.nom_fr_fr.ToLower().Contains(term.term.ToLower())).Select(s => new {label = s.nom_fr_fr, value = s.nom_fr_fr});
            return new JsonResult(res);
        }

        public JsonResult GetHTPIMembre([FromBody] Term term){
            var res = _context.Membre.Where(p => p.Prenom.ToLower().Contains(term.term.ToLower()) || p.Nom.ToLower().Contains(term.term.ToLower())).ToList();
            var res1 = res.Select(s => new {label = s.Nom+" "+s.Prenom, value = s.ID_HTPI}).ToList();
            return new JsonResult(res1);
        }

        [HttpPost]
        public async Task<JsonResult> UploadFile(IList<IFormFile> files)
        {
            Upload upload = new Upload();
            foreach (IFormFile source in files)
            {
                string filename = ContentDispositionHeaderValue.Parse(source.ContentDisposition).FileName.Trim('"');

                filename = this.EnsureCorrectFilename(filename);

                using (FileStream output = System.IO.File.Create(this.GetPathAndFilename(filename)))
                await source.CopyToAsync(output);

                string filePath = this.GetPathAndFilename(filename);
                upload.Date = DateTime.Now;
                upload.FileName = filename;
                upload.Uri = filePath;
                _context.Upload.Add(upload);
                _context.SaveChanges();
            }

            return new JsonResult(upload);
        }

        public async Task<IActionResult> Download(int? id)
        {
            Upload upload = _context.Upload.Find(id);
            if(upload != null){
                string filename = upload.FileName;
                if (filename == null)
                    return Content("filename not present");

                var path = Path.Combine(
                            Directory.GetCurrentDirectory(),
                            "wwwroot/uploads/", filename);

                var memory = new MemoryStream();
                using (var stream = new FileStream(path, FileMode.Open))
                {
                    await stream.CopyToAsync(memory);
                }
                memory.Position = 0;
                return File(memory, GetContentType(path), Path.GetFileName(path));
            }else{
                return Content("filename not present"); 
            }
        }

        private string EnsureCorrectFilename(string filename)
        {
            if (filename.Contains("\\"))
                filename = filename.Substring(filename.LastIndexOf("\\") + 1);

            return filename;
        }

        private string GetPathAndFilename(string filename)
        {
            return this._hostingEnvironment.WebRootPath + "\\uploads\\" + filename;
        }

        public IActionResult CarteMembre()
        {
            return View();
        }

        // POST: Membre/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID, Appellation, Nom, Prenom, DateNaissance, Nationnalite, Profession, Adresse, CodePostal, Ville, MembrePays, PieceIdentite, Email, TelephoneFixe, TelephoneMobile, NumCompatibleMobileMoney, OperateurID, MembreReference, AccepteCharteMembre, ID_HTPI")] Membre membre)
        {
            //if (ModelState.IsValid)
            //{
            Membre _membre = new Membre();
            _membre.Appellation = membre.Appellation;
            _membre.Nom = membre.Nom;
            _membre.Prenom = membre.Prenom;
            _membre.DateNaissance = membre.DateNaissance;
            _membre.Nationnalite = membre.Nationnalite;
            _membre.Profession = membre.Profession;
            _membre.Adresse = membre.Adresse;
            _membre.CodePostal = membre.CodePostal;
            _membre.Ville = membre.Ville;

            Pays pays = _context.Pays.FirstOrDefault(p => p.nom_fr_fr.ToLower().Contains(membre.MembrePays.ToLower()));
            if(pays != null){
                _membre.PaysID = pays.ID;
            }

            PieceIdentite pieceIdentite = membre.PieceIdentite;
            PieceIdentite _pieceIdentite = new PieceIdentite();

            _pieceIdentite.TypePieceIdentiteID = pieceIdentite.TypePieceIdentiteID;
            _pieceIdentite.AutreTypePieceIdentiteID = pieceIdentite.AutreTypePieceIdentiteID;
            _pieceIdentite.NumPieceIdentite = pieceIdentite.NumPieceIdentite;

            pays = _context.Pays.FirstOrDefault(p => p.nom_fr_fr.ToLower().Contains(pieceIdentite.DelivrancePays.ToLower()));
            if(pays != null){
                _pieceIdentite.PaysDelivranceID = pays.ID;
            }
            
            _pieceIdentite.DateDelivrance = pieceIdentite.DateDelivrance;
            _pieceIdentite.DateExpiration = pieceIdentite.DateExpiration;
            _pieceIdentite.UploadPieceIdentiteID = pieceIdentite.UploadPieceIdentiteID;
            _pieceIdentite.TypeJustDomicileID = pieceIdentite.TypeJustDomicileID == 0 ? null : pieceIdentite.TypeJustDomicileID;
            _pieceIdentite.AutreTypeJustDomicileID = pieceIdentite.AutreTypeJustDomicileID;
            _pieceIdentite.UploadJustificatifDomicileID = pieceIdentite.UploadJustificatifDomicileID;
            _pieceIdentite.UploadActeDeNaissanceID = pieceIdentite.UploadActeDeNaissanceID;

            _context.Add(_pieceIdentite);
            _context.SaveChanges();

            _membre.PieceIdentiteID = _pieceIdentite.ID;

            _membre.Email = membre.Email;
            _membre.TelephoneFixe = membre.TelephoneFixe;
            _membre.TelephoneMobile = membre.TelephoneMobile;
            _membre.NumCompatibleMobileMoney = membre.NumCompatibleMobileMoney;
            _membre.OperateurID = membre.OperateurID;

            if(membre.MembreReference != null){
                Membre membreReference = _context.Membre.FirstOrDefault(m => (m.Nom+" "+m.Prenom).ToLower().Contains(membre.MembreReference.ToLower()));
                if(membreReference != null)
                    _membre.PersonneReferenceID = membreReference.ID;
            }
            //_membre.AccepteCharteMembre = membre.AccepteCharteMembre;
            _context.Add(_membre);
            await _context.SaveChangesAsync();

            _membre.ID_HTPI = "HTPI_"+_membre.ID;
            _context.Update(_membre);
            await _context.SaveChangesAsync();

            //return RedirectToAction(nameof(Index));
            //}
            ViewBag.Operateurs = _context.Operateur.ToList();
            ViewBag.TypePieceIdentites = _context.TypePieceIdentite.ToList();
            ViewBag.TypeJustDomiciles = _context.TypeJustificatifDomicile.ToList();
            ViewBag.Pays = _context.Pays.ToList();
            ViewBag.Saved = 1;

            return View(_membre);
        }

        // GET: Membre/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {

Controllers/PaiementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HTPIFoundation.Models;

namespace HTPIFoundation.Controllers
{
    public class PaiementController : Controller
    {
        private readonly HTPIFoundationContext _context;

        public PaiementController(HTPIFoundationContext context)
        {
            _context = context;
        }

        // GET: Paiement
        public async Task<IActionResult> Index(int?id)
        {
            if (id == null) {
                return View(await _context.Paiement.ToListAsync());
            }
            return View(await _context.Paiement.Where(p => p.MembreID == id).ToListAsync());
        }

        // GET: Paiement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiement
                .SingleOrDefaultAsync(m => m.ID == id);
            var membre = await _context.Membre.SingleOrDefaultAsync(m => m.ID == paiement.MembreID);
            ViewBag.membre = membre;
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        // GET: Paiement/Create
        public IActionResult Create(int?id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var membre = _context.Membre.SingleOrDefault(c => c.ID == id);
            if (membre == null)
            {
                return NotFound();
            }
            ViewBag.id = membre.ID;
            ViewBag.nomPrenom = membre.Nom + " " + membre.Prenom;
            return View();
        }

        public IActionResult Recu(int? id)
        {
            var paiement = _context.Paiement.Find(id);
            var membre = _context.Membre.Where(m => m.ID == paiement.MembreID);
            ViewBag.paiment = paiement;
            ViewBag.membre = membre;
            if (id == null)
            {
                return NotFound();
            }
            return  View();
        }

        // POST: Paiement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MembreID,MontantPayer,DatePayement,MoyenPayement,IDTransaction,AvanceAccord,MontantAvance,MembreReference")] Paiement paiement)
        {
            //if (ModelState.IsValid)
            if (paiement!=null)
            {
                if (paiement.MembreReference != null)
                {
                    Membre membreReference = _context.Membre.FirstOrDefault(m => (m.Nom + " " + m.Prenom).ToLower().Contains(paiement.MembreReference.ToLower()));
                    if (membreReference != null)
                        paiement.MembreAvanceID = membreReference.ID;
                }
                _context.Add(paiement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paiement);
        }

        // GET: Paiement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiement.SingleOrDefaultAsync(m => m.ID == id);
            if (paiement == null)
            {
                return NotFound();
            }
            return View(paiement);
        }

        // POST: Paiement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,MembreID,MontantPayer,DatePayement,MoyenPayement,IDTransaction,AvanceAccord,MontantAvance,MembreAvanceID")] Paiement paiement)
        {
            if (id != paiement.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paiement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaiementExists(paiement.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paiement);
        }

        // GET: Paiement/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiement
                .SingleOrDefaultAsync(m => m.ID == id);
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        // POST: Paiement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paiement = await _context.Paiement.SingleOrDefaultAsync(m => m.ID == id);
            _context.Paiement.Remove(paiement);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaiementExists(int id)
        {
            return _context.Paiement.Any(e => e.ID == id);
        }
    }
}

Views/Paiement/Create.cshtml
@model HTPIFoundation.Models.Paiement

@{
    ViewData["Title"] = "Create";
}


<div class="page-container">
    <h1>HTPI, Foundation Internationale enregistrée sous le numéro 11451859 au Third Floor, 207
        <small>Regent Street, Londres, Royaume Uni, W1B3HH atteste par la présente que</small>
    </h1>


    <form asp-action="Create">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <h2>PAIEMENT</h2>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="MembreID" class="control-label"></label>
                    <input type="hidden" asp-for="MembreID" class="form-control" value="@ViewBag.id" />
                    <input for="MembreID1" class="form-control" value="@ViewBag.nomPrenom" disabled />
                    <span asp-validation-for="MembreID" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="MontantPayer" class="control-label"></label>
                    <input asp-for="MontantPayer" class="form-control" />
                    <span asp-validation-for="MontantPayer" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="DatePayement" class="control-label"></label>
                    <input asp-for="DatePayement" class="form-control" type="date"/>
                    <span asp-validation-for="DatePayement" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group ">
                    <label asp-for="MoyenPayement" class="control-label"></label>
                    <div class="checkbox" >
                        @Html.RadioButtonFor(model => model.MoyenPayement, 1, new { id = "MoyenPayement1" })
                        <label for="MoyenPayement1" class="control-label">En espèces</label>
                        @Html.RadioButtonFor(model => model.MoyenPayement, 0, new { id = "MoyenPayement2" })
                        <label for="MoyenPayement2" class="control-label">Par Mobile Money</label>
                    </div>
                    <span asp-validation-for="MoyenPayement" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="IDTransaction" class="control-label"></label>
                    <input asp-for="IDTransaction" class="form-control" />
                    <span asp-validation-for="IDTransaction" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="AvanceAccord" class="control-label"></label>
                    <div class="checkbox">
                        @Html.RadioButtonFor(model => model.AvanceAccord, 1, new { id = "AvanceAccord1" })
                        <label for="AvanceAccord1" class="control-label">Oui</label>
                        @Html.RadioButtonFor(model => model.AvanceAccord, 0, new { id = "AvanceAccord2" })
                        <label for="AvanceAccord2" class="control-label">Non</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="MontantAvance" class="control-label"></label>
                    <input asp-for="MontantAvance" class="form-control" />
                    <span asp-validation-for="MontantAvance" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 col-sm-12">
                <div class="form-group form-inline">
                    <label asp-for="MembreReference" class="control-label"></label>
                    <input asp-for="MembreReference" class="form-control" />
                    <span asp-validation-for="MembreReference" class="text-danger"></span>
                </div>
            </div>
        </div>


        <br><br>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <strong>A  reconnu avoir lu, compris et signé ce  jour la Charte de membre de la Fondation HTPI et s’engage à la respecter.</strong>
            </div>
        </div>
        <br><br>
        <div class="row">
            <div class="col-md-6 col-sm-12 text-left">
                <span class="rememberer">(*) Champs Obligatoires</span>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class=" btn btn text-right Submit btn-block">
                    <input type="submit" value="Valider" class="btn btn-default text-center pull-right" />
                </div>
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-controller="Membre" asp-action="Index">Back to List</a>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script type="text/javascript">
    $(function(){
        $("#MembreReference").typeahead({
                hint: true,
                highlight: true,
                minLength: 1,
                source: function (request, response) {
                    $.ajax({
                        url: '/Membre/GetHTPIMembre/',
                        data: "{ 'term': '" + request + "'}",
                        dataType: "json",
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            items = [];
                            map = {};
                            $.each(data, function (i, item) {
                                var id = item.value;
                                var name = item.label;
                                map[name] = { id: id, name: name };
                                items.push(name);
                            });
                            response(items);
                            $(".dropdown-menu").css("height", "auto");
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                updater: function (item) {
                    $('#GetHTPIMembre').val(map[item].id);
                    return item;
                }
            });
    });
    </script>
}

Views/Paiement/Delete.cshtml
@model HTPIFoundation.Models.Paiement

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paiement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MontantPayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MontantPayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DatePayement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DatePayement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MoyenPayement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MoyenPayement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IDTransaction)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IDTransaction)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AvanceAccord)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AvanceAccord)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MontantAvance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MontantAvance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MembreAvanceID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MembreAvanceID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Paiement/Edit.cshtml
@model HTPIFoundation.Models.Paiement

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Paiement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MontantPayer" class="control-label"></label>
                <input asp-for="MontantPayer" class="form-control" />
                <span asp-validation-for="MontantPayer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePayement" class="control-label"></label>
                <input asp-for="DatePayement" class="form-control" />
                <span asp-validation-for="DatePayement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoyenPayement" class="control-label"></label>
                <input asp-for="MoyenPayement" class="form-control" />
                <span asp-validation-for="MoyenPayement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IDTransaction" class="control-label"></label>
                <input asp-for="IDTransaction" class="form-control" />
                <span asp-validation-for="IDTransaction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="Avance_accord" /> @Html.DisplayNameFor(model => model.AvanceAccord)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="MontantAvance" class="control-label"></label>
                <input asp-for="MontantAvance" class="form-control" />
                <span asp-validation-for="MontantAvance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MembreAvanceID" class="control-label"></label>
                <input asp-for="MembreAvanceID" class="form-control" />
                <span asp-validation-for="MembreAvanceID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Paiement/Index.cshtml
@model IEnumerable<HTPIFoundation.Models.Paiement>
@{
    ViewData["Title"] = "Index";
}


<div class="page-container">
    <h1 class="with-btn">Liste
        <small>des paiements</small>
        <a asp-action="Create" class="btn">Create New</a>
    </h1>

<div class="table-responsive">
<table class="table table-condensed">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MontantPayer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DatePayement)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MoyenPayement)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IDTransaction)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AvanceAccord)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MontantAvance)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MembreAvanceID)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MontantPayer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePayement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoyenPayement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDTransaction)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvanceAccord)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MontantAvance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MembreAvanceID)
            </td>
            <td class="actions">
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
</div>